export interface QuestionDef {
  title: string
  timeframe?: string
  items: { id: string; text: string; options?: { value: number; label: string }[] }[]
  options: { value: number; label: string }[]
}

export const SURVEY_QUESTIONS: Record<string, Record<string, QuestionDef>> = {
  promis_physical_function_4a_v2: {
    en: {
      title: 'Physical Function',
      items: [
        { id: 'pf1', text: 'Are you able to do chores such as vacuuming or yard work?' },
        { id: 'pf2', text: 'Are you able to go up and down stairs at a normal pace?' },
        { id: 'pf3', text: 'Are you able to go for a walk of at least 15 minutes?' },
        { id: 'pf4', text: 'Are you able to run errands and shop?' },
      ],
      options: [
        { value: 5, label: 'Without any difficulty' },
        { value: 4, label: 'With a little difficulty' },
        { value: 3, label: 'With some difficulty' },
        { value: 2, label: 'With much difficulty' },
        { value: 1, label: 'Unable to do' },
      ],
    },
    es: {
      title: 'Capacidad de funcionamiento físico',
      items: [
        { id: 'pf1', text: '¿Puede realizar tareas, como pasar la aspiradora o trabajar en el jardín?' },
        { id: 'pf2', text: '¿Puede subir y bajar escaleras a un paso normal?' },
        { id: 'pf3', text: '¿Puede salir a caminar durante 15 minutos por lo menos?' },
        { id: 'pf4', text: '¿Puede hacer mandados (recados) y compras?' },
      ],
      options: [
        { value: 5, label: 'Sin dificultad' },
        { value: 4, label: 'Con poca dificultad' },
        { value: 3, label: 'Con alguna dificultad' },
        { value: 2, label: 'Con mucha dificultad' },
        { value: 1, label: 'No puedo hacerlo' },
      ],
    },
  },
  promis_anxiety_4a_v1: {
    en: {
      title: 'Anxiety',
      timeframe: 'In the past 7 days...',
      items: [
        { id: 'anx1', text: 'I felt fearful.' },
        { id: 'anx2', text: 'I found it hard to focus on anything other than my anxiety.' },
        { id: 'anx3', text: 'My worries overwhelmed me.' },
        { id: 'anx4', text: 'I felt uneasy.' },
      ],
      options: [
        { value: 1, label: 'Never' },
        { value: 2, label: 'Rarely' },
        { value: 3, label: 'Sometimes' },
        { value: 4, label: 'Often' },
        { value: 5, label: 'Always' },
      ],
    },
    es: {
      title: 'Ansiedad',
      timeframe: 'En los últimos 7 días...',
      items: [
        { id: 'anx1', text: 'Sentí miedo' },
        { id: 'anx2', text: 'Tuve dificultad para concentrarme en otra cosa que no fuera mi ansiedad' },
        { id: 'anx3', text: 'Mis inquietudes fueron demasiado para mí' },
        { id: 'anx4', text: 'Me sentí intranquilo/a' },
      ],
      options: [
        { value: 1, label: 'Nunca' },
        { value: 2, label: 'Rara vez' },
        { value: 3, label: 'Algunas veces' },
        { value: 4, label: 'A menudo' },
        { value: 5, label: 'Siempre' },
      ],
    },
  },
  promis_depression_4a_v1: {
    en: {
      title: 'Depression',
      timeframe: 'In the past 7 days...',
      items: [
        { id: 'dep1', text: 'I felt worthless.' },
        { id: 'dep2', text: 'I felt helpless.' },
        { id: 'dep3', text: 'I felt depressed.' },
        { id: 'dep4', text: 'I felt hopeless.' },
      ],
      options: [
        { value: 1, label: 'Never' },
        { value: 2, label: 'Rarely' },
        { value: 3, label: 'Sometimes' },
        { value: 4, label: 'Often' },
        { value: 5, label: 'Always' },
      ],
    },
    es: {
      title: 'Depresión',
      timeframe: 'En los últimos 7 días...',
      items: [
        { id: 'dep1', text: 'Sentí que no valía nada' },
        { id: 'dep2', text: 'Me sentí indefenso/a (que no podía hacer nada para ayudarme)' },
        { id: 'dep3', text: 'Me sentí deprimido/a' },
        { id: 'dep4', text: 'Me sentí desesperanzado/a' },
      ],
      options: [
        { value: 1, label: 'Nunca' },
        { value: 2, label: 'Rara vez' },
        { value: 3, label: 'Algunas veces' },
        { value: 4, label: 'A menudo' },
        { value: 5, label: 'Siempre' },
      ],
    },
  },
  promis_fatigue_4a_v1: {
    en: {
      title: 'Fatigue',
      timeframe: 'In the past 7 days...',
      items: [
        { id: 'fat1', text: 'I feel fatigued.' },
        { id: 'fat2', text: 'I have trouble starting things because I am tired.' },
        { id: 'fat3', text: 'How run-down did you feel on average?' },
        { id: 'fat4', text: 'How fatigued were you on average?' },
      ],
      options: [
        { value: 1, label: 'Not at all' },
        { value: 2, label: 'A little bit' },
        { value: 3, label: 'Somewhat' },
        { value: 4, label: 'Quite a bit' },
        { value: 5, label: 'Very much' },
      ],
    },
    es: {
      title: 'Agotamiento',
      timeframe: 'En los últimos 7 días...',
      items: [
        { id: 'fat1', text: 'Me siento agotado/a' },
        { id: 'fat2', text: 'Tengo dificultad para comenzar las cosas porque estoy cansado/a' },
        { id: 'fat3', text: '¿Qué tan rendido/a se sintió en promedio?' },
        { id: 'fat4', text: '¿Qué tan agotado/a estuvo en promedio?' },
      ],
      options: [
        { value: 1, label: 'Nada' },
        { value: 2, label: 'Un poco' },
        { value: 3, label: 'Algo' },
        { value: 4, label: 'Mucho' },
        { value: 5, label: 'Muchísimo' },
      ],
    },
  },
  promis_sleep_4a_v1: {
    en: {
      title: 'Sleep Disturbance',
      timeframe: 'In the past 7 days...',
      items: [
        { id: 'slp1', text: 'My sleep quality was...', options: [
          { value: 5, label: 'Very poor' },
          { value: 4, label: 'Poor' },
          { value: 3, label: 'Fair' },
          { value: 2, label: 'Good' },
          { value: 1, label: 'Very good' },
        ]},
        { id: 'slp2', text: 'My sleep was refreshing.', options: [
          { value: 5, label: 'Not at all' },
          { value: 4, label: 'A little bit' },
          { value: 3, label: 'Somewhat' },
          { value: 2, label: 'Quite a bit' },
          { value: 1, label: 'Very much' },
        ]},
        { id: 'slp3', text: 'I had a problem with my sleep.', options: [
          { value: 1, label: 'Not at all' },
          { value: 2, label: 'A little bit' },
          { value: 3, label: 'Somewhat' },
          { value: 4, label: 'Quite a bit' },
          { value: 5, label: 'Very much' },
        ]},
        { id: 'slp4', text: 'I had difficulty falling asleep.', options: [
          { value: 1, label: 'Not at all' },
          { value: 2, label: 'A little bit' },
          { value: 3, label: 'Somewhat' },
          { value: 4, label: 'Quite a bit' },
          { value: 5, label: 'Very much' },
        ]},
      ],
      options: [
        { value: 1, label: 'Not at all' },
        { value: 2, label: 'A little bit' },
        { value: 3, label: 'Somewhat' },
        { value: 4, label: 'Quite a bit' },
        { value: 5, label: 'Very much' },
      ],
    },
    es: {
      title: 'Alteración del sueño',
      timeframe: 'En los últimos 7 días...',
      items: [
        { id: 'slp1', text: 'La calidad de mi sueño fue', options: [
          { value: 5, label: 'Muy mala' },
          { value: 4, label: 'Mala' },
          { value: 3, label: 'Pasable' },
          { value: 2, label: 'Buena' },
          { value: 1, label: 'Muy buena' },
        ]},
        { id: 'slp2', text: 'Mi sueño fue reparador', options: [
          { value: 5, label: 'Nada' },
          { value: 4, label: 'Un poco' },
          { value: 3, label: 'Algo' },
          { value: 2, label: 'Mucho' },
          { value: 1, label: 'Muchísimo' },
        ]},
        { id: 'slp3', text: 'Tuve problemas para dormir', options: [
          { value: 1, label: 'Nada' },
          { value: 2, label: 'Un poco' },
          { value: 3, label: 'Algo' },
          { value: 4, label: 'Mucho' },
          { value: 5, label: 'Muchísimo' },
        ]},
        { id: 'slp4', text: 'Tuve dificultad para dormirme', options: [
          { value: 1, label: 'Nada' },
          { value: 2, label: 'Un poco' },
          { value: 3, label: 'Algo' },
          { value: 4, label: 'Mucho' },
          { value: 5, label: 'Muchísimo' },
        ]},
      ],
      options: [
        { value: 1, label: 'Nada' },
        { value: 2, label: 'Un poco' },
        { value: 3, label: 'Algo' },
        { value: 4, label: 'Mucho' },
        { value: 5, label: 'Muchísimo' },
      ],
    },
  },
  promis_social_4a_v1: {
    en: {
      title: 'Ability to Participate in Social Roles and Activities',
      timeframe: 'In the past 7 days...',
      items: [
        { id: 'soc1', text: 'I have trouble doing all of my regular leisure activities with others.' },
        { id: 'soc2', text: 'I have trouble doing all of the family activities that I want to do.' },
        { id: 'soc3', text: 'I have trouble doing all of my usual work.' },
        { id: 'soc4', text: 'I have trouble doing all of the activities with friends that I want to do.' },
      ],
      options: [
        { value: 5, label: 'Never' },
        { value: 4, label: 'Rarely' },
        { value: 3, label: 'Sometimes' },
        { value: 2, label: 'Usually' },
        { value: 1, label: 'Always' },
      ],
    },
    es: {
      title: 'Capacidad para participar en roles y actividades sociales',
      timeframe: 'En los últimos 7 días...',
      items: [
        { id: 'soc1', text: 'Tengo problemas para realizar con otras personas todas mis actividades habituales de tiempo libre' },
        { id: 'soc2', text: 'Tengo problemas para realizar todas las actividades con mi familia que quiero hacer' },
        { id: 'soc3', text: 'Tengo problemas para realizar todo mi trabajo habitual (incluya el trabajo en el hogar)' },
        { id: 'soc4', text: 'Tengo problemas para realizar todas las actividades con mis amigos/as que quiero hacer' },
      ],
      options: [
        { value: 5, label: 'Nunca' },
        { value: 4, label: 'Rara vez' },
        { value: 3, label: 'Algunas veces' },
        { value: 2, label: 'A menudo' },
        { value: 1, label: 'Siempre' },
      ],
    },
  },
  promis_pain_interference_4a_v1: {
    en: {
      title: 'Pain Interference',
      timeframe: 'In the past 7 days, how much did pain interfere with your...',
      items: [
        { id: 'pi1', text: 'How much did pain interfere with your day to day activities?' },
        { id: 'pi2', text: 'How much did pain interfere with work around the home?' },
        { id: 'pi3', text: 'How much did pain interfere with your ability to participate in social activities?' },
        { id: 'pi4', text: 'How much did pain interfere with your household chores?' },
      ],
      options: [
        { value: 1, label: 'Not at all' },
        { value: 2, label: 'A little bit' },
        { value: 3, label: 'Somewhat' },
        { value: 4, label: 'Quite a bit' },
        { value: 5, label: 'Very much' },
      ],
    },
    es: {
      title: 'Efectos del dolor',
      timeframe: 'En los últimos 7 días…',
      items: [
        { id: 'pi1', text: '¿En qué medida el dolor interfirió en sus actividades diarias?' },
        { id: 'pi2', text: '¿En qué medida el dolor interfirió en el trabajo en el hogar?' },
        { id: 'pi3', text: '¿En qué medida el dolor interfirió en su capacidad para participar en actividades sociales?' },
        { id: 'pi4', text: '¿En qué medida el dolor interfirió en sus tareas domésticas?' },
      ],
      options: [
        { value: 1, label: 'Nada' },
        { value: 2, label: 'Un poco' },
        { value: 3, label: 'Algo' },
        { value: 4, label: 'Mucho' },
        { value: 5, label: 'Muchísimo' },
      ],
    },
  },
  phq9: {
    en: {
      title: 'Depression Screen (PHQ-9)',
      timeframe: 'Over the last 2 weeks, how often have you been bothered by any of the following problems?',
      items: [
        { id: 'phq_1', text: 'Little interest or pleasure in doing things' },
        { id: 'phq_2', text: 'Feeling down, depressed, or hopeless' },
        { id: 'phq_3', text: 'Trouble falling or staying asleep, or sleeping too much' },
        { id: 'phq_4', text: 'Feeling tired or having little energy' },
        { id: 'phq_5', text: 'Poor appetite or overeating' },
        { id: 'phq_6', text: 'Feeling bad about yourself or that you are a failure or have let yourself or your family down' },
        { id: 'phq_7', text: 'Trouble concentrating on things, such as reading the newspaper or watching television' },
        { id: 'phq_8', text: 'Moving or speaking so slowly that other people could have noticed, or the opposite being so fidgety or restless that you have been moving around a lot more than usual' },
        { id: 'phq_9', text: 'Thoughts that you would be better off dead, or of hurting yourself in some way' },
      ],
      options: [
        { value: 0, label: 'Not at all' },
        { value: 1, label: 'Several days' },
        { value: 2, label: 'More than half the days' },
        { value: 3, label: 'Nearly every day' },
      ],
    },
    es: {
      title: 'Cuestionario de Salud del Paciente (PHQ-9)',
      timeframe: 'Durante las últimas 2 semanas, con que frecuencia le han molestado los siguientes problemas?',
      items: [
        { id: 'phq_1', text: 'Poco interés o placer en hacer las cosas' },
        { id: 'phq_2', text: 'Sentirse desanimado, deprimido, o sin esperanza' },
        { id: 'phq_3', text: 'Problemas para quedarse dormido o dormir demasiado' },
        { id: 'phq_4', text: 'Sentirse cansado o con poca energía' },
        { id: 'phq_5', text: 'Poco apetito o comer en exceso' },
        { id: 'phq_6', text: 'Sentirse mal consigo mismo, o que es un fracaso, o que ha quedado mal consigo mismo o con su familia' },
        { id: 'phq_7', text: 'Problemas para concentrarse en cosas tales como leer el periódico o ver televisión' },
        { id: 'phq_8', text: 'Moverse o hablar tan lento que otras personas lo habrían notado, o lo contrario' },
        { id: 'phq_9', text: 'Pensamientos de que estaría mejor muerto, o de que se haría daño de alguna manera' },
      ],
      options: [
        { value: 0, label: 'Para nada' },
        { value: 1, label: 'Varios días' },
        { value: 2, label: 'Más de la mitad de los días' },
        { value: 3, label: 'Casi todos los días' },
      ],
    },
  },
  gad7: {
    en: {
      title: 'Anxiety Screen (GAD-7)',
      timeframe: 'Over the last 2 weeks, how often have you been bothered by the following problems?',
      items: [
        { id: 'gad_1', text: 'Feeling nervous, anxious, or on edge' },
        { id: 'gad_2', text: 'Not being able to stop or control worrying' },
        { id: 'gad_3', text: 'Worrying too much about different things' },
        { id: 'gad_4', text: 'Trouble relaxing' },
        { id: 'gad_5', text: 'Being so restless that it is hard to sit still' },
        { id: 'gad_6', text: 'Becoming easily annoyed or irritable' },
        { id: 'gad_7', text: 'Feeling afraid as if something awful might happen' },
      ],
      options: [
        { value: 0, label: 'Not at all' },
        { value: 1, label: 'Several days' },
        { value: 2, label: 'More than half the days' },
        { value: 3, label: 'Nearly every day' },
      ],
    },
    es: {
      title: 'Trastorno de Ansiedad Generalizada (GAD-7)',
      timeframe: 'Durante las últimas 2 semanas, con que frecuencia le han molestado los siguientes problemas?',
      items: [
        { id: 'gad_1', text: 'Sentirse nervioso, ansioso, o al límite' },
        { id: 'gad_2', text: 'No poder dejar de preocuparse o no poder controlar la preocupación' },
        { id: 'gad_3', text: 'Preocuparse demasiado por diversas cosas' },
        { id: 'gad_4', text: 'Problemas para relajarse' },
        { id: 'gad_5', text: 'Estar tan inquieto que resulta difícil quedarse quieto' },
        { id: 'gad_6', text: 'Molestarse o ponerse irritable fácilmente' },
        { id: 'gad_7', text: 'Sentir miedo, como si algo terrible fuera a pasar' },
      ],
      options: [
        { value: 0, label: 'Para nada' },
        { value: 1, label: 'Varios días' },
        { value: 2, label: 'Más de la mitad de los días' },
        { value: 3, label: 'Casi todos los días' },
      ],
    },
  },
  tsk11: {
    en: {
      title: 'Tampa Scale for Kinesiophobia',
      timeframe: 'Please indicate how much you agree with each of the following statements.',
      items: [
        { id: 'tsk_1',  text: "I'm afraid that I might injure myself if I exercise." },
        { id: 'tsk_2',  text: "If I were to try to overcome it, my pain would increase." },
        { id: 'tsk_3',  text: "My body is telling me I have something dangerously wrong." },
        { id: 'tsk_4',  text: "People aren't taking my medical condition seriously enough." },
        { id: 'tsk_5',  text: "My accident has put my body at risk for the rest of my life." },
        { id: 'tsk_6',  text: "Pain always means I have injured my body." },
        { id: 'tsk_7',  text: "Simply being careful that I do not make any unnecessary movements is the safest thing I can do to prevent my pain from worsening." },
        { id: 'tsk_8',  text: "I wouldn't have this much pain if there weren't something potentially dangerous going on in my body." },
        { id: 'tsk_9',  text: "Pain lets me know when to stop exercising so that I don't injure myself." },
        { id: 'tsk_10', text: "I can't do all the things normal people do because it's too easy for me to get injured." },
        { id: 'tsk_11', text: "No one should have to exercise when he/she is in pain." },
      ],
      options: [
        { value: 1, label: 'Strongly Disagree' },
        { value: 2, label: 'Disagree' },
        { value: 3, label: 'Agree' },
        { value: 4, label: 'Strongly Agree' },
      ],
    },
    es: {
      title: 'Escala de Tampa para la Kinesiofobia',
      timeframe: 'Por favor indique cuanto esta de acuerdo con cada una de las siguientes afirmaciones.',
      items: [
        { id: 'tsk_1',  text: 'Me da miedo lastimarme si hago ejercicio.' },
        { id: 'tsk_2',  text: 'Si tratara de superarlo, mi dolor aumentaría.' },
        { id: 'tsk_3',  text: 'Mi cuerpo me está diciendo que algo está peligrosamente mal.' },
        { id: 'tsk_4',  text: 'La gente no está tomando mi condición médica suficientemente en serio.' },
        { id: 'tsk_5',  text: 'Mi accidente ha puesto mi cuerpo en riesgo por el resto de mi vida.' },
        { id: 'tsk_6',  text: 'El dolor siempre significa que he lesionado mi cuerpo.' },
        { id: 'tsk_7',  text: 'Simplemente ser cuidadoso de no hacer movimientos innecesarios es lo más seguro que puedo hacer para evitar que mi dolor empeore.' },
        { id: 'tsk_8',  text: 'No tendría tanto dolor si no hubiera algo potencialmente peligroso ocurriendo en mi cuerpo.' },
        { id: 'tsk_9',  text: 'El dolor me avisa cuándo debo parar de hacer ejercicio para no lastimarme.' },
        { id: 'tsk_10', text: 'No puedo hacer todas las cosas que hace la gente normal porque me lastimo fácilmente.' },
        { id: 'tsk_11', text: 'Nadie debería tener que hacer ejercicio cuando tiene dolor.' },
      ],
      options: [
        { value: 1, label: 'Muy en desacuerdo' },
        { value: 2, label: 'En desacuerdo' },
        { value: 3, label: 'De acuerdo' },
        { value: 4, label: 'Muy de acuerdo' },
      ],
    },
  },
  pcs: {
    en: {
      title: 'Pain Catastrophizing Scale',
      timeframe: 'When I have pain, I think about it in the following ways. Please indicate the degree to which you have these thoughts and feelings.',
      items: [
        { id: 'pcs_1',  text: "I worry all the time about whether the pain will end." },
        { id: 'pcs_2',  text: "I feel I can't go on." },
        { id: 'pcs_3',  text: "It's terrible and I think it's never going to get any better." },
        { id: 'pcs_4',  text: "It's awful and I feel that it overwhelms me." },
        { id: 'pcs_5',  text: "I feel I can't stand it anymore." },
        { id: 'pcs_6',  text: "I become afraid that the pain will get worse." },
        { id: 'pcs_7',  text: "I keep thinking of other painful events." },
        { id: 'pcs_8',  text: "I anxiously want the pain to go away." },
        { id: 'pcs_9',  text: "I can't seem to keep it out of my mind." },
        { id: 'pcs_10', text: "I keep thinking about how much it hurts." },
        { id: 'pcs_11', text: "I keep thinking about how badly I want the pain to stop." },
        { id: 'pcs_12', text: "There's nothing I can do to reduce the intensity of the pain." },
        { id: 'pcs_13', text: "I wonder whether something serious may happen." },
      ],
      options: [
        { value: 0, label: 'Not at all' },
        { value: 1, label: 'To a slight degree' },
        { value: 2, label: 'To a moderate degree' },
        { value: 3, label: 'To a great degree' },
        { value: 4, label: 'All the time' },
      ],
    },
    es: {
      title: 'Escala de Catastrofización del Dolor',
      timeframe: 'Cuando tengo dolor, pienso en ello de las siguientes formas. Por favor indique en que medida tiene estos pensamientos y sentimientos.',
      items: [
        { id: 'pcs_1',  text: 'Me preocupo todo el tiempo de si el dolor terminará.' },
        { id: 'pcs_2',  text: 'Siento que no puedo seguir adelante.' },
        { id: 'pcs_3',  text: 'Es terrible y creo que nunca va a mejorar.' },
        { id: 'pcs_4',  text: 'Es horrible y siento que me abruma.' },
        { id: 'pcs_5',  text: 'Siento que no puedo aguantar mas.' },
        { id: 'pcs_6',  text: 'Me da miedo de que el dolor empeore.' },
        { id: 'pcs_7',  text: 'Sigo pensando en otros eventos dolorosos.' },
        { id: 'pcs_8',  text: 'Quiero ansiosamente que el dolor desaparezca.' },
        { id: 'pcs_9',  text: 'No puedo sacarlo de mi mente.' },
        { id: 'pcs_10', text: 'Sigo pensando cuanto me duele.' },
        { id: 'pcs_11', text: 'Sigo pensando cuanto quiero que el dolor se detenga.' },
        { id: 'pcs_12', text: 'No hay nada que pueda hacer para reducir la intensidad del dolor.' },
        { id: 'pcs_13', text: 'Me pregunto si puede ocurrir algo grave.' },
      ],
      options: [
        { value: 0, label: 'Para nada' },
        { value: 1, label: 'En pequeña medida' },
        { value: 2, label: 'En mediana medida' },
        { value: 3, label: 'En gran medida' },
        { value: 4, label: 'Todo el tiempo' },
      ],
    },
  },
  gic: {
    en: {
      title: 'Global Impression of Change',
      items: [{
        id: 'gic_1',
        text: 'Since starting the functional restoration program, how would you describe your OVERALL condition?',
        options: [
          { value: 1, label: 'A lot better' },
          { value: 2, label: 'Better' },
          { value: 3, label: 'Slightly better' },
          { value: 4, label: "No change, I'm about the same as when I started the program" },
          { value: 5, label: 'Slightly worse' },
          { value: 6, label: 'Worse' },
          { value: 7, label: 'A lot worse' },
        ],
      }],
      options: [],
    },
    es: {
      title: 'Impresión Global de Cambio',
      items: [{
        id: 'gic_1',
        text: 'Desde que comenzó el programa de restauración funcional, ¿cómo describiría su condición EN GENERAL?',
        options: [
          { value: 1, label: 'Mucho mejor' },
          { value: 2, label: 'Mejor' },
          { value: 3, label: 'Ligeramente mejor' },
          { value: 4, label: 'Sin cambios, estoy más o menos igual que cuando comencé el programa.' },
          { value: 5, label: 'Ligeramente peor' },
          { value: 6, label: 'Peor' },
          { value: 7, label: 'Mucho peor' },
        ],
      }],
      options: [],
    },
  },
  pain_nrs: {
    en: {
      title: 'Pain Intensity',
      items: [{ id: 'nrs', text: 'On average, how would you rate your pain over the past 7 days?' }],
      options: Array.from({ length: 11 }, (_, i) => ({
        value: i,
        label: i === 0 ? '0 - No pain' : i === 10 ? '10 - Worst pain imaginable' : String(i),
      })),
    },
    es: {
      title: 'Intensidad del dolor',
      timeframe: 'En los últimos 7 días…',
      items: [{ id: 'nrs', text: 'En promedio, ¿cómo calificaría su dolor?' }],
      options: Array.from({ length: 11 }, (_, i) => ({
        value: i,
        label: i === 0 ? '0 - Ningún dolor' : i === 10 ? '10 - El peor dolor imaginable' : String(i),
      })),
    },
  },
}
